#!/bin/bash
# Ensure supabase files exist
if [ ! -f "src/integrations/supabase/client.ts" ]; then
  mkdir -p src/integrations/supabase
  cat > src/integrations/supabase/client.ts << 'EOF'
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF
fi

if [ ! -f "src/integrations/supabase/types.ts" ]; then
  cat > src/integrations/supabase/types.ts << 'EOF'
export type Database = {
  public: {
    Tables: {
      [key: string]: any;
    };
    Views: {
      [key: string]: any;
    };
    Functions: {
      [key: string]: any;
    };
    Enums: {
      [key: string]: any;
    };
  };
};
EOF
fi

echo "✅ Supabase files verified"
